app {
  rabbitmq {
    host = "127.0.0.1"
    port = 5672
    user = "guest"
    password = "guest"
    queue = "orders.placed"
    exchange = "orders.exchange"
    routing-key = "orders.placed"
  }

  db {
    url = "jdbc:postgresql://localhost:5432/polyglider"
    user = "postgres"
    password = "postgres"
  }

  consumer {
    queue-size = 1000
    workers = 4
  }
}
