using System.Text.Json;
using System.Text.RegularExpressions;
using Xunit;

namespace gateway_api_cs_tests;

/// <summary>
/// Verifies that the C# gateway produces an OrderPlaced message that satisfies
/// the consumer contract defined by the Scala engine in contracts/pacts/.
///
/// The pact file is generated by running `sbt test` in processing-engine-scala/
/// and must exist before these tests run.
/// </summary>
public class OrderPlacedEventProviderTests
{
    private static readonly JsonSerializerOptions CamelCase = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
    };

    // AppContext.BaseDirectory is bin/Debug/net9.0/ — four levels up reaches repo root.
    private static readonly string PactFilePath = Path.GetFullPath(Path.Combine(
        AppContext.BaseDirectory,
        "..", "..", "..", "..",
        "contracts", "pacts", "scala-engine-cs-gateway.json"));

    private static readonly Regex UuidPattern = new(
        @"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
        RegexOptions.IgnoreCase | RegexOptions.Compiled);

    [Fact]
    [Trait("Category", "Contract")]
    public void PactFile_Exists()
    {
        Assert.True(
            File.Exists(PactFilePath),
            $"Pact file not found at: {PactFilePath}\n" +
            "Run 'sbt test' in processing-engine-scala/ first to generate it.");
    }

    [Fact]
    [Trait("Category", "Contract")]
    public void OrderPlacedEvent_SerializesAllFiveFieldsInCamelCase()
    {
        var evt = new OrderPlacedEvent(
            EventId: Guid.Parse("11111111-1111-4111-8111-111111111111"),
            Sku: "SKU-001",
            Quantity: 5,
            CustomerId: Guid.Parse("22222222-2222-4222-8222-222222222222"),
            Timestamp: new DateTime(2024, 1, 15, 10, 30, 0, DateTimeKind.Utc));

        var json = JsonSerializer.Serialize(evt, CamelCase);
        var doc = JsonDocument.Parse(json).RootElement;

        Assert.True(doc.TryGetProperty("eventId", out var eventId), "Missing field: eventId");
        Assert.True(doc.TryGetProperty("sku", out var sku), "Missing field: sku");
        Assert.True(doc.TryGetProperty("quantity", out var quantity), "Missing field: quantity");
        Assert.True(doc.TryGetProperty("customerId", out var customerId), "Missing field: customerId");
        Assert.True(doc.TryGetProperty("timestamp", out var timestamp), "Missing field: timestamp");

        Assert.Equal(JsonValueKind.String, eventId.ValueKind);
        Assert.Matches(UuidPattern, eventId.GetString()!);

        Assert.Equal(JsonValueKind.String, sku.ValueKind);
        Assert.Equal("SKU-001", sku.GetString());

        Assert.Equal(JsonValueKind.Number, quantity.ValueKind);
        Assert.Equal(5, quantity.GetInt32());

        Assert.Equal(JsonValueKind.String, customerId.ValueKind);
        Assert.Matches(UuidPattern, customerId.GetString()!);

        Assert.Equal(JsonValueKind.String, timestamp.ValueKind);
        Assert.True(DateTimeOffset.TryParse(timestamp.GetString(), out _),
            $"timestamp '{timestamp.GetString()}' is not a valid ISO-8601 date");
    }

    [Fact]
    [Trait("Category", "Contract")]
    public void OrderPlacedEvent_SerializedShape_MatchesPactConsumerContract()
    {
        if (!File.Exists(PactFilePath))
            throw new SkipException("Pact file not found — run 'sbt test' first.");

        var pact = JsonDocument.Parse(File.ReadAllText(PactFilePath)).RootElement;
        var messages = pact.GetProperty("messages");
        Assert.True(messages.GetArrayLength() > 0, "Pact file has no messages");

        var messageBody = messages[0].GetProperty("contents");

        string[] expectedKeys = ["eventId", "sku", "quantity", "customerId", "timestamp"];
        foreach (var key in expectedKeys)
            Assert.True(messageBody.TryGetProperty(key, out _),
                $"Pact message body is missing field: {key}");

        Assert.Matches(UuidPattern, messageBody.GetProperty("eventId").GetString()!);
        Assert.Matches(UuidPattern, messageBody.GetProperty("customerId").GetString()!);
        Assert.Equal(JsonValueKind.Number, messageBody.GetProperty("quantity").ValueKind);
    }

    private sealed class SkipException(string reason) : Exception(reason);
}
