name: Scala CI

on:
  push:
    branches-ignore: [ "main" ]
    paths:
      - "processing-engine-scala/**"
      - "contracts/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "processing-engine-scala/**"
      - "contracts/**"
  workflow_dispatch:

permissions:
  contents: write
  dependency-graph: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "sbt"

      - name: Set up sbt
        uses: sbt/setup-sbt@v1

      - name: Run tests
        working-directory: processing-engine-scala
        run: sbt test

      - name: Upload pact file
        uses: actions/upload-artifact@v4
        with:
          name: pact-file
          path: contracts/pacts/scala-engine-cs-gateway.json

      - name: Upload dependency graph
        uses: scalacenter/sbt-dependency-submission@ab086b50c947c9774b70f39fc7f6e20ca2706c91
        continue-on-error: true
        with:
          working-directory: processing-engine-scala
